### ISSUE TITLE
Possible issue with defaults?

### ISSUE THREAD

**Issue by dbashford** [dpeukert/mimosa-replace#1]
I haven't tried it yet, but at first glance I noticed that you reference `.defaults`, https://github.com/dpeukert/mimosa-replace/blob/master/src/index.js#L35, but the config.js doesn't seem to have one?

Not having defaults is ok, but referencing it when its not there probably isn't.  It can just be left out.

**Comment by dpeukert** [comment]
Yeah, I originally used them but took them out and forgot about it. I'll fix it tonight together with some other things.

Thanks for noticing :)

**Comment by dpeukert** [comment]
I'm close to releasing an update, but I have a question. Does `inputFileText` always output the initial content of the file?

**Comment by dbashford** [comment]
Usually, yes.

But modules can modify the input text.  You may have a coffeescript application, and you may have something, a macro maybe, that needs to be transformed before the Coffeescript compiler is used.  That's a case where the input text would be updated as it is the Coffeescript compilers job to turn input text to output text.

Sent from myMail for iOS
